fix: fixed import urls for windows
asyncapi/glee pull request #229
Opened 2022-01-10 19:12 UTC by sudoshreyansh

**Description**

- Fixed absolute file URLs in dynamic imports

**Related issue(s)**

Fixes #222

2022-01-17 15:36 UTC, fmvilas requested changes

2022-01-17 15:36 UTC, fmvilas commented on src/lib/functions.ts
> +import { gleeMessageToFunctionEvent } from './util.js'
```suggestion
import { getConfigs } from './configs.js'
import { logWarningMessage } from './logger'
import GleeMessage from './message'
import { GleeFunction } from './index'
import Glee from './glee'
import { gleeMessageToFunctionEvent } from './util'
```

2022-01-17 15:36 UTC, fmvilas commented on src/lib/functions.ts
> +import { gleeMessageToFunctionEvent } from './util.js'
This one was actually my fault while merging with `master`.

2022-01-17 15:36 UTC, fmvilas commented on src/lib/lifecycleEvents.ts
> +import { arrayHasDuplicates } from './util.js'
```suggestion
import { GleeFunctionEvent, GleeFunctionReturn, GleeFunctionReturnSend } from './index'
import { logInfoMessage } from './logger'
import GleeMessage from './message'
import { arrayHasDuplicates } from './util'
```

2022-01-17 15:36 UTC, fmvilas commented on src/lib/lifecycleEvents.ts
> +import { arrayHasDuplicates } from './util.js'
Same as above

2022-01-17 15:37 UTC, fmvilas requested changes

2022-01-17 15:37 UTC, fmvilas commented on src/lib/functions.ts
> +import { getConfigs } from './configs.js'
```suggestion
import { getConfigs } from './configs'
```

2022-01-17 15:40 UTC, fmvilas commented
@sudoshreyansh do you think we can easily add a test to watch for it?

2022-01-17 16:03 UTC, fmvilas commented
I just realized we should add a test for this. This PR is failing on MacOS X and probably Linux too.

I get this error while running the `dummy` example on MacOS X:

![Captura de pantalla 2022-01-17 a las 16 48 35](https://user-images.githubusercontent.com/242119/149802944-ad06315e-2053-4d31-9f25-2174cb195a5b.png)

2022-01-31 12:31 UTC, sudoshreyansh commented
@fmvilas the change to commonjs modules in `tsconfig.json` in the master branch fixed the issue. Now it runs fine for me in Windows Node v17.3.

But the change introduced another issue. When creating a new app using `create-glee-app`, the package.json is set to ES6 modules because of which using `require()` on the functions and lifecycles, creates an error:

![image](https://user-images.githubusercontent.com/44190883/151792272-7f533264-363a-4ba7-aaa3-49a0a9361448.png)

And there also is a problem with reading the package.json when running apps created from `create-glee-app`:

![image](https://user-images.githubusercontent.com/44190883/151794115-f3f94291-f62a-48ec-9887-4d3957586f21.png)

Do I fix the latter one in this PR? And I can open a PR for the former in create-glee-app repository ?

2022-01-31 16:47 UTC, fmvilas commented
Yeah, we have to fix this on the create-glee-app repository instead.

2022-03-07 12:41 UTC, closed without merging