fix: added log for invalid returned data from functions
asyncapi/glee pull request #273
Opened 2022-03-15 09:11 UTC by sudoshreyansh

**Description**

- added check and log for invalid data returned from functions

**Related issue(s)**
Fixes #270

2022-03-15 15:32 UTC, fmvilas requested changes
I think we should do better here instead of just checking for the existence of `send` or `reply`. What if I return an object like this:

```js
return {
  send: 10,
}
```

It may be a good idea to use JSON Schema for this and we already have `ajv` installed as a dependency :)

2022-03-16 05:53 UTC, sudoshreyansh commented
Ok I have made the changes.

@fmvilas do you want to log the errors too while validating the returned value or just the invalid message?

2022-03-16 18:37 UTC, fmvilas requested changes

2022-03-16 18:37 UTC, fmvilas commented on src/lib/functions.ts
> +    payload: { type: ['string', 'object'] },
Payload can be anything so I'd just make it like this:

```suggestion
    payload: {},
```

2022-03-16 18:37 UTC, fmvilas commented on src/lib/functions.ts
> +      additionProperties: { type: 'string' }
```suggestion
      additionalProperties: { type: 'string' }
```

2022-03-16 18:37 UTC, fmvilas commented on src/lib/functions.ts
> +      })
```suggestion
      const err = new GleeError({
        humanReadableError,
        errors,
      })
      err.message = `Function ${operationId} returned invalid data.`
      logError(err, {
        highlightedWords: [operationId]
      })
      
      
```

You probably have to import GleeError above. If I didn't commit any mistake 😅  that should give a better hint to the user on what actually went wrong.

2022-03-17 09:13 UTC, sudoshreyansh commented
@fmvilas I have made the changes.

2022-03-21 12:50 UTC, fmvilas approved these changes
Great stuff 👏

2022-03-21 12:50 UTC, fmvilas commented
/rtm

2022-03-21 12:51 UTC, merged