fix: make some improvements
asyncapi/glee pull request #363
Opened 2022-11-28 12:07 UTC by KhudaDad414

**Description**
I was working on an example project to get myself familiarize with glee I think these changes will fix a few bugs and make some improvements.
- glee will support multiple messages in channels.
- the glee types will be available for typescript projects.

2022-11-28 16:49 UTC, fmvilas requested changes

2022-11-28 16:49 UTC, fmvilas commented on src/adapters/ws/index.ts
>            this.emit('connect', { name: this.name(), adapter: this, connection: ws, channel: pathname })
We should get rid of this `connect` event. As per documentation, `connect` is only triggered when Glee is a client but in this case it behaves as a server.

2022-11-28 16:49 UTC, fmvilas commented on src/index.ts
> +        const schema = {oneOf: channel.publish().messages().map(message => message.payload().json())} as any;
```suggestion
        const schema = {oneOf: channel.publish().messages().map(message => message.payload().json())} as any
```

2022-11-28 16:49 UTC, fmvilas commented on src/index.ts
> +      const schema = {oneOf: channel.subscribe().messages().map(message => message.payload().json())} as any;
```suggestion
      const schema = {oneOf: channel.subscribe().messages().map(message => message.payload().json())} as any
```

2022-11-28 16:49 UTC, fmvilas commented on src/lib/configs.ts
>        return console.error(e)
```suggestion
    return console.error(e)
```

2022-11-28 16:49 UTC, fmvilas commented on src/lib/lifecycleEvents.ts
>          res.send.forEach((event: GleeFunctionReturnSend) => {
Wouldn't it make more sense to do this directly?

```suggestion
        res?.send?.forEach((event: GleeFunctionReturnSend) => {
```

This way we remove the `if` clause.

2022-11-30 06:18 UTC, fmvilas approved these changes
LGTM 👍 

Pinging @Souvikns @sudoshreyansh @Ruchip16 @atharvagadkari05 too in case they want to review.

2022-11-30 08:45 UTC, Souvikns approved these changes

2022-12-01 14:26 UTC, KhudaDad414 commented
/rtm

2022-12-01 14:27 UTC, merged