refactor: refactor mqtt _connect() method
asyncapi/glee pull request #400
Opened 2023-03-14 01:21 UTC by oviecodes

**Description**
Refactor the mqtt adapter _connect() method

**Related issue(s)**
#397

2023-03-14 10:48 UTC, Souvikns approved these changes
Good job @oviecodes! Looks neat 👍🏼

2023-03-14 11:01 UTC, KhudaDad414 requested changes
Left a few comments.
Regarding the package-lock.json Please regenerate it with a newer version of NPM that uses lockfile version 2.

2023-03-14 14:30 UTC, oviecodes commented on src/adapters/mqtt/index.ts
> +    await this.listenToEvents({ protocolVersion })
I was thinking for future purposes, in case there was a need to pass other variables. I could change it if it's not necessary.

2023-03-16 12:47 UTC, oviecodes commented
@KhudaDad414 I've made the requested changes

2023-03-16 13:40 UTC, KhudaDad414 approved these changes
LGTM! let's wait for @fmvilas approval.

2023-03-24 09:55 UTC, oviecodes commented
@KhudaDad414 , the package-lock.json in the glee repo is using lockfile version 2.

2023-03-27 15:41 UTC, KhudaDad414 commented
@oviecodes the tests are failing 🤔

2023-03-27 16:05 UTC, oviecodes commented
> @oviecodes the tests are failing 🤔

I'm trying to figure out why, I'm looking at it right now @KhudaDad414

2023-03-27 22:15 UTC, oviecodes commented
I fixed it @KhudaDad414 , it was a problem with package-lock.json file. The test should pass now

2023-04-17 14:16 UTC, KhudaDad414 commented
hey @oviecodes Please resolve the conflicts so we can merge this. :)

2023-04-20 09:00 UTC, oviecodes commented
@KhudaDad414 done

2023-04-20 10:30 UTC, KhudaDad414 approved these changes
LGTM!

2023-04-20 10:32 UTC, KhudaDad414 commented
/rtm

2023-04-20 10:32 UTC, merged