feat: added AMQP support
asyncapi/glee pull request #456
Opened 2023-06-01 11:36 UTC by AceTheCreator

This PR adds support for AMQP 0-9-1.

cc @fmvilas @Souvikns @KhudaDad414

2023-06-13 08:50 UTC, KhudaDad414 requested changes
Left a few comments.

2023-06-20 11:43 UTC, AceTheCreator commented on src/adapters/amqp/index.ts
> +      vhost: serverBindings?.vhost || '/',
Yea, we don't. I was playing around trying a default connection. I'll definitely get rid of it

2023-06-20 11:44 UTC, AceTheCreator commented on src/adapters/amqp/index.ts
> +    const resolved = false
You're right!

2023-06-20 18:26 UTC, AceTheCreator commented
@KhudaDad414 i updated this PR, have a look

2024-06-30 00:20 UTC, closed without merging