docs: adds getting started guide
asyncapi/glee pull request #483
Opened 2023-07-26 14:57 UTC by afzal442

* Part of #480

2023-09-11 08:45 UTC, Souvikns requested changes
@afzal442 left some comments, I have a question:
what is `glee-template.md` and why do we need it?

2023-09-11 18:16 UTC, afzal442 commented on docs/getting-started.md
> +To send a WebSocket request with a payload e.g. `{"name":"souvik", "time": "1567906535"}` to `ws://localhost:3000/greet`, open Postman and checkout the endpoint:
while working on it myself, I found it lgtm. and ultimately I am pointing to your github repo for reference. let's keep it as is. 😄

2023-09-12 13:56 UTC, afzal442 commented on docs/glee-template.md
> +<CodeBlock>
@Souvikns I think it is github .md that can't render it.
e.g.
https://github.com/asyncapi/website/blob/master/pages/docs/tutorials/getting-started/hello-world.md

2023-09-12 14:12 UTC, afzal442 commented on docs/getting-started.md
> +
@Souvikns I removed that intro part from that other PR and added it here like nextjs docs follows

2023-09-12 14:18 UTC, afzal442 commented
> what is `glee-template.md` and why do we need it?

that is separate file which gives clear understanding of glee-template step by step like [this](https://github.com/asyncapi/website/blob/master/pages/docs/tutorials/getting-started/hello-world.md).

2023-09-13 09:36 UTC, Souvikns requested changes
Good work @afzal442, just update the image and example and we can merge this.

2023-09-13 09:36 UTC, Souvikns commented on docs/getting-started.md
> +To send a WebSocket request with a payload e.g. `{"name":"souvik", "time": "1567906535"}` to `ws://localhost:3000/greet`, open Postman and checkout the endpoint:
```suggestion
To send a WebSocket request with a payload e.g. `{"name":"SomeOtherName", "time": "1567906535"}` to `ws://localhost:3000/greet`, open Postman and checkout the endpoint:
```

Everything else is fine, just remove my name I think you followed my example which is good, but remove my name 🤣. Remove it from the image as well, please.

2023-09-15 07:49 UTC, Souvikns approved these changes
Good job @afzal442 👍🏼

2023-09-19 06:25 UTC, Souvikns commented
/rtm

2023-09-19 06:26 UTC, merged