docs: makes glee internal features into pages
asyncapi/glee pull request #522
Opened 2023-09-14 15:05 UTC by afzal442

**Description**
This PR recreates glee internal features into pages

**Related issue(s)**
* Related to #431 
* Part of #480

2023-10-05 12:59 UTC, Souvikns requested changes
Should these docs go under the pages folder just like the [installation doc](https://github.com/asyncapi/glee/blob/master/docs/pages/installation.md) also is the pages folder for rending on the website?

2023-10-06 06:33 UTC, afzal442 commented
Hey @Souvikns sorry for the delay

> Should these docs go under the pages folder ...
I think let's first render the existing pages like installation guide and see how it looks

> is the pages folder for rending on the website?
Yes using github action as described here https://github.com/asyncapi/glee/issues/481

2023-10-09 13:54 UTC, KhudaDad414 commented on docs/app-structure.md
@afzal442 why are we removing this file? 🤔

2023-10-09 18:50 UTC, afzal442 commented on docs/app-structure.md
Sorry @KhudaDad414! not removing. but recreating it into pages.

2023-11-16 10:06 UTC, KhudaDad414 approved these changes

2023-11-16 10:06 UTC, KhudaDad414 commented
Let's wait for @Souvikns review.

2023-11-20 19:21 UTC, afzal442 commented
pinging @Souvikns 😃

2023-11-21 02:06 UTC, Souvikns approved these changes

2023-11-21 03:32 UTC, afzal442 commented
/rtm

2023-11-21 03:32 UTC, merged