fix: migrate the pages markdown files into pages folder
asyncapi/glee pull request #538
Opened 2023-10-12 11:58 UTC by afzal442

- Related to #483 
- Part of #480

2023-10-12 14:47 UTC, afzal442 commented
Hi, I think it is ready to be reviewed.

cc @Souvikns @KhudaDad414

2023-10-12 14:53 UTC, KhudaDad414 requested changes

2023-10-12 14:53 UTC, KhudaDad414 commented on docs/pages/glee-template.md
I am not sure where this page fits in the documentation.
before making changes to the structure. I suggest you open a discussion and write down the things that we discussed. plus a blue-print of the final documentation. and how the documentation should be navigated.

2023-10-12 17:38 UTC, afzal442 commented on docs/pages/glee-template.md
Thanks for your suggestion. I have raised an [issue](https://github.com/asyncapi/glee/issues/481) on auto-deployment using gh action. If Animesh is not able to proceed with it, I will create a PR to resolve that next week. 
once it's get merged, we'll be able to view pages rendered on asyncapi website like below and we can customise those if required. 
![image](https://github.com/asyncapi/glee/assets/11625672/e2f8a993-056d-40b7-9db9-f634729819c4)

Also I will be opening a discussion on that taking into consideration of glee v3.
WDYT? cc @Souvikns let's merge this for now.

2023-11-09 15:01 UTC, afzal442 commented on docs/pages/glee-template.md
@KhudaDad414 we are considering `/docs/pages/*.md` files to be displayed for the website. What do you think about it now?

2023-11-09 15:45 UTC, KhudaDad414 commented on docs/pages/glee-template.md
left some comment here: https://github.com/asyncapi/glee/pull/564
lets do this 💪

2023-11-21 11:09 UTC, KhudaDad414 approved these changes
LGTM

2023-11-21 15:03 UTC, afzal442 commented
/rtm

2023-11-21 15:03 UTC, merged