fix: use HTTP bindings correctly
asyncapi/glee pull request #579
Opened 2023-11-15 16:52 UTC by KhudaDad414

**Description**

- [ ] Refactor HTTP client code.
- [ ] Make sure HTTP bindings work with client HTTP.
- [ ] Refactor HTTP server code.
- [ ] Make sure HTTP bindings are applied to the server.
- [ ] Make sure the request/reply works with the HTTP protocol.

**Related issue(s)**
Resolves #553 
Blocked by #551

2023-11-21 15:36 UTC, KhudaDad414 commented
@fmvilas @Souvikns please take a look when you have the time.

2023-11-23 10:56 UTC, fmvilas requested changes

2023-11-23 10:56 UTC, fmvilas commented on examples/http-test/asyncapi.yaml
> +x-remoteServers:
On another PR, not this one, can we get rid of this and move it to the glee.config.js file? It feels weird to see it as part of the AsyncAPI file.

2023-11-23 10:57 UTC, fmvilas approved these changes
Approving as my only comment should not block this PR.

2023-11-23 16:27 UTC, KhudaDad414 commented
/rtm

2023-11-23 16:27 UTC, merged